samples: config/samples.csv
out: results

tools:
  gzip:
    extension: "gz"
    compression:
      opts: "-c -{lvl}"
      range:
        min: 1
        max: 9
      default: 6
    decompression:
      opts: "-c -d"
  bzip2:
    extension: "bz2"
    compression:
      opts: "-z -c -{lvl}"
      range:
        min: 1
        max: 9
      default: 9
    decompression:
      opts: "-d -c"
  xz:
    extension: "xz"
    compression:
      opts: "-z -c -{lvl}"
      range:
        min: 1
        max: 9
      default: 6
    decompression:
      opts: "-d -c"
  zstd:
    extension: "zst"
    compression:
      opts: "-c -{lvl}"
      range:
        min: 1
        max: 19
      default: 3
    decompression:
      opts: "-c -d"
  brotli:
    extension: "br"
    compression:
      opts: "-c -q {lvl}"
      range:
        min: 1
        max: 11
      default: 11
    decompression:
      opts: "-c -d"

containers:
  fastq_dl: "docker://quay.io/biocontainers/fastq-dl:2.0.1--pyhdfd78af_0"